name: Debug
on:
  pull_request:
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT"
      - name: Post PR to \#dev-pr webhook
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_X_JOBS_DEV }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
               "attachments": [
                    {
                        "mrkdwn_in": ["text"],
                        "color": "#3679a6",
                        "pretext": "Dependabot opened new PR: ",
                        "author_name": "Dependabot 🤖",
                        "author_link": " ",
                        "author_icon": "https://placeimg.com/16/16/people",
                        "title": "${{ github.event.pull_request.title }}",
                        "title_link": "${{ github.event.pull_request.html_url }}",
                        "fields":
                        [
                            {
                                "title": "repository",
                                "value": "${{ github.event.pull_request.head.repo.name }} ",
                                "short": false
                            }
                        ],
                        "thumb_url": "http://placekitten.com/g/200/200",
                        "footer": "footer",
                        "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                        "ts": 123456789
                    }
                  ]
            }
