name: Dependabot New PR
on:
  pull_request:
    types:
     - opened
     - reopened
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: read maintainers.json
        id: read-maintainers
        # reads maintainers array and map them to their slack userIds "mentions" (see slack api https://api.slack.com/reference/surfaces/formatting#mentioning-users)
        run: |
          echo "maintainers=$(cat maintainers.json | jq '.[] | to_entries | .[].value' | jq --slurp -r '. | join(" ")')" >> "$GITHUB_OUTPUT"
      - name: Post PR to \#dev-pr webhook
        if: always() # continue even if read-maintainers failed for some reason
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_PR }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          MAINTAINERS: ${{ steps.read-maintainers.outputs.maintainers }}
        with:
          payload: |
            {
               "attachments": [
                    {
                        "mrkdwn_in": ["text"],
                        "color": "#3679a6",
                        "pretext": "Dependabot opened new PR: ",
                        "author_name": "Dependabot 🤖",
                        "author_link": " ",
                        "author_icon": "https://manage.cove.is/imgs/favicon.png",
                        "title": "${{ github.event.pull_request.title }}",
                        "title_link": "${{ github.event.pull_request.html_url }}",
                        "fields":
                        [
                            {
                                "title": "repository",
                                "value": "${{ github.event.pull_request.head.repo.name }} ",
                                "short": false
                            },
                            {
                                "title": "maintainers",
                                "value": "${{ env.MAINTAINERS || 'no one' }}",
                                "short": true
                            }
                        ],
                        "thumb_url": "https://manage.cove.is/imgs/favicon.png",
                        "footer": " ",
                        "footer_icon": "https://manage.cove.is/imgs/favicon.png",
                        "ts": 123456789
                    }
                  ]
            }
  #############################################
  notify-all:
  #############################################
      uses: livelyhood/cove-workflows/.github/workflows/notify.yml@main
      needs:
        - dependabot
      if: ${{ always() && contains(needs.*.result, 'failure') }}
      secrets: inherit
      with:
        failure: true
