name: Release CI
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run lint command
        run: npm run lint
  release:
    needs: [lint]
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run build command
        run: npm run build
      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          COMMIT_ASSETS: dist
          GIT_AUTHOR_NAME: "BetaHuhn Bot"
          GIT_AUTHOR_EMAIL: "bot@mxis.ch"
          GIT_COMMITTER_NAME: "BetaHuhn Bot"
          GIT_COMMITTER_EMAIL: "bot@mxis.ch"
